---
# Import variables.
- name: Import variables
  include_vars: "{{ ansible_os_family }}.yml"

# Import tasks.
- name: Import tasks RedHat
  include_tasks: task_RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Import tasks Ubuntu
  include_tasks: task_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Nginx service.
- name: Nginx service
  service: 
    name: nginx
    state: started
    enabled: yes