---
# Import variables.
- name: Import variables
  include_vars: "{{ ansible_os_family }}.yml"

# Import tasks.
- name: Import tasks RedHat
  include_tasks: task_RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Import tasks Ubuntu
  include_tasks: task_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Nginx service.
- name: Nginx service
  service: 
    name: nginx
    state: started
    enabled: yes

# Nginx Verify is listening on port 80
- name: Nginx Verify port 80
  wait_for:
    port: 80
    timeout: 2